#!/bin/bash
https://picodotdev.github.io/blog-bitix/2021/01/las-metodologias-oocss-bem-y-smacss-para-organizar-los-estilos-css/#:~:text=La%20metodolog%C3%ADa%20Object%2DOriented%20CSS,Separar%20contenedor%20del%20contenido.
